from .auth_blueprint import auth_blueprint
from .student_blueprint import  student_blueprint
from .sysadmin_blueprint import sysadmin_blueprint
from .university_admin_blueprint import university_admin_blueprint